name: OIDC Test
on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        type: choice
        options:
          - qa
          - prod
        default: qa
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.environment || 'dev'}}
    env:
      Environment: ${{github.event.inputs.environment || 'dev'}}
    steps:
      - name: Printing Enviornment
        run : echo "Enviornment is:$Environment"
      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{secrets.AWS_ROLE}}
          aws-region: us-east-2
      - name : To list S3
        run: |
              aws s3 ls
    
    
